### PR TITLE
[ACA-4122] Sites API response to return relation with groups

### PR DESCRIPTION
**Pull request by dhrn**
https://alfresco.atlassian.net/browse/ACA-4122

depends:- https://github.com/Alfresco/rest-api-explorer/pull/110

### CODE REVIEW

**Review by eromano — APPROVED** [review]

**Review by gavincornwell — COMMENTED** [review]
To be honest I feel very nervous about this PR but I might not be fully understanding the purpose of the changes.

If I understand correctly you're trying to return the list of groups each site member belongs to and show that group's role within this site!?

Personally, I think we need to review the use case/requirements here, I'm happy to have a discussion if you put something in my calendar.

**Review by skopf — CHANGES_REQUESTED** [review]
We cannot do this. The UX should have been rejected in the first place. You can expect that a user is in 10s of Ks of groups, each giving the user access to this site.

**Comment by eromano** [comment]
can we add this request as an option ?

**Comment by eromano** [comment]
I am closing this PR for now I think we can archive a similar experience in the FE also if is not perfect under the performance side

**Pull request closed without merging**
