### PR TITLE
[SEARCH-2677] Extract SearchEngineResultSet and SearchEngineResultMetadata interfaces

### PR DESCRIPTION
**Pull request by agazzarini**

### CODE REVIEW

**Review by killerboot — COMMENTED** [review]
Is it possible to move the REST API related classes like (SolrJSONResultSet) to remote-api project?

**Comment by agazzarini** [comment]
> Is it possible to move the REST API related classes like (SolrJSONResultSet) to remote-api project?

Hi Alex, as far as I see, we should move there all "*.search.impl" packages, which is a huge amount of classes. Can't we do that as a separate ticket? Being a "remote" project, it is not blocking the facet issue

**Comment by killerboot** [comment]
> > Is it possible to move the REST API related classes like (SolrJSONResultSet) to remote-api project?
> 
> Hi Alex, as far as I see, we should move there all "*.search.impl" packages, which is a huge amount of classes. Can't we do that as a separate ticket? Being a "remote" project, it is not blocking the facet issue

Please create a separate ticket for that.

**Comment by agazzarini** [comment]
> > > Is it possible to move the REST API related classes like (SolrJSONResultSet) to remote-api project?
> > 
> > 
> > Hi Alex, as far as I see, we should move there all "*.search.impl" packages, which is a huge amount of classes. Can't we do that as a separate ticket? Being a "remote" project, it is not blocking the facet issue
> 
> Please create a separate ticket for that.

https://alfresco.atlassian.net/browse/SEARCH-2732

**Comment by agazzarini** [comment]
@killerboot I'm not sure about the build status, it has been cancelled but everything is green there. What do you think about merging this PR? Elia and Alessandro need that for their tickets

**Comment by killerboot** [comment]
Please check that SS 2.0 still works with community repo with this change before merging.

**Review by killerboot — APPROVED** [review]

**Pull request merged**
