### PR TITLE
ACS-855 : Long running patch in ACS 7.0.0.A2 upgrade

### PR DESCRIPTION
**Pull request by DenisGabriela**
- revert  changes on AlfrescoCreate-RepoTables.sql and Schema-Reference-ALF.xml files done in [REPO-4547's pull request](https://github.com/Alfresco/alfresco-community-repo/commit/cba9899215182b9e0516e92a67ce47217e072c79)
   - remove all patch.db-V6.3-remove-alf_server-table DB scripts

### CODE REVIEW

**Review by killerboot — APPROVED** [review]

**Comment by killerboot** [comment]
I thought that it is easier to use "git revert" :)

**Comment by skopf** [comment]
I can see some indexes being removed by this PR, like for example:
{code}
    KEY idx_alf_txn_ctms_sc (commit_time_ms),
    key idx_alf_txn_id_ctms (id, commit_time_ms)
{code}

Shouldn't we keep these indexes?

**Comment by DenisGabriela** [comment]
> I can see some indexes being removed by this PR, like for example:
> {code}
> KEY idx_alf_txn_ctms_sc (commit_time_ms),
> key idx_alf_txn_id_ctms (id, commit_time_ms)
> {code}
> 
> Shouldn't we keep these indexes?

@skopf Thanks for pointing it out. I updated the PR.

**Comment by skopf** [comment]
@killerboot The original commit did not just remove these tables, columns and FK indexes, they also added some additional indexes. IIRC, then these indexes have been put there to improve indexing speed with SOLR.
I think you are more familiar with these performance improvements. Can you please make sure that by reverting the DB change we did not break any of these perf improvements?
If you have no objections, I am ok to merge this.

**Review by skopf — APPROVED** [review]
LGTM. We can merge if @killerboot has no objections

**Comment by killerboot** [comment]
@skopf I don't think that any new indexes were added in scope of REPO-4547:
https://github.com/Alfresco/alfresco-community-repo/commit/cba9899215182b9e0516e92a67ce47217e072c79 
https://github.com/Alfresco/alfresco-enterprise-repo/commit/44c57eb63ea31fe9f71e2e34021baebf03e11af9
https://github.com/Alfresco/alfresco-enterprise-repo/commit/48c410e72095d566792758d94d83d906c6e3d0f4

So, unless I'm missing something, it is just required to bring back the tables in the same state as they were in 6.2.N. The DAO layer is still removed.

The best approach would be to perform an upgrade test from last 6.2 to 7.0 and see if there are any schema differences.

**Comment by DenisGabriela** [comment]
@killerboot , @skopf we've done the upgrade test and I can confirm there are no schema differences.

**Review by cristianturlica — APPROVED** [review]
LGTM

**Pull request merged**
