### PR TITLE
Add unit test to look for unreferenced test classes.

### PR DESCRIPTION
**Pull request by tpage-alfresco**
It's very unusual that we write a test class which should not also be added to a test suite.

### CODE REVIEW

**Comment by tpage-alfresco** [comment]
Currently this new test is failing since 69 test classes need investigation:
```
Unreferenced test class count: 69
class org.alfresco.messaging.camel.CamelRoutesTest
class org.alfresco.repo.site.SiteServiceTestHuge
class org.alfresco.repo.security.permissions.PermissionCheckedCollectionTest
class org.alfresco.repo.node.MetadataEncryptorTests
class org.alfresco.repo.content.caching.CachingContentStoreSpringTest
class org.alfresco.repo.bulkimport.impl.AbstractBulkImportTests
class org.alfresco.repo.tenant.MultiTAdminServiceImplTest
class org.alfresco.repo.version.VersionableAspectTest
class org.alfresco.repo.workflow.activiti.AbstractActivitiComponentTest
class org.alfresco.repo.content.LimitedStreamCopierTest
class org.alfresco.repo.workflow.activiti.properties.ActivitiPriorityPropertyHandlerTest
class org.alfresco.repo.domain.node.NodePropertyHelperTest
class org.alfresco.repo.search.impl.solr.DbOrIndexSwitchingQueryLanguageTest
class org.alfresco.repo.domain.schema.script.ScriptBundleExecutorImplTest
class org.alfresco.repo.action.executer.CheckOutActionExecuterTest
class org.alfresco.repo.cache.TransactionStatsTest
class org.alfresco.repo.rendition2.TransformationOptionsConverterTest
class org.alfresco.repo.notification.NotificationServiceImplSystemTest
class org.alfresco.repo.rendition.executer.AbstractRenderingEngineTest
class org.alfresco.repo.node.integrity.IntegrityEventTest
class org.alfresco.repo.content.transform.RemoteTransformerClientTest
class org.alfresco.repo.action.scheduled.FreeMarkerModelLuceneFunctionTest
class org.alfresco.repo.workflow.activiti.ActivitiTaskComponentTest
class org.alfresco.repo.workflow.activiti.ActivitiSpringTest
class org.alfresco.repo.search.impl.querymodel.impl.db.DBQueryTest
class org.alfresco.repo.audit.access.NodeChangeTest
class org.alfresco.repo.security.authority.script.ScriptAuthorityService_RegExTest
class org.alfresco.repo.action.executer.TransformActionExecuterTest
class org.alfresco.repo.action.constraint.ActionParameterConstraintTest
class org.alfresco.repo.tenant.AbstractTenantRoutingContentStoreTest
class org.alfresco.repo.management.subsystems.CryptodocSwitchableApplicationContextFactoryTest
class org.alfresco.repo.action.evaluator.HasChildEvaluatorTest
class org.alfresco.repo.content.MimetypeMapContentTest
class org.alfresco.repo.rendition2.RenditionEventProcessorTest
class org.alfresco.repo.content.filestore.BucketAwareFileContentStoreTest
class org.alfresco.repo.cache.InMemoryCacheStatisticsTest
class org.alfresco.repo.dictionary.DictionaryDAOTest
class org.alfresco.repo.action.executer.TakeOwnershipActionExecuterTest
class org.alfresco.repo.search.impl.querymodel.impl.db.NodePermissionAssessorLimitsTest
class org.alfresco.repo.content.metadata.xml.XmlMetadataExtracterTest
class org.alfresco.repo.action.evaluator.HasTagEvaluatorTest
class org.alfresco.repo.solr.SOLRTrackingComponentUnitTest
class org.alfresco.repo.content.filestore.VolumeAwareFileContentStoreTest
class org.alfresco.repo.security.sync.LDAPUserRegistryTest
class org.alfresco.opencmis.AlfrescoCmisExceptionInterceptorTest
class org.alfresco.repo.search.impl.querymodel.impl.db.DBQueryEngineTest
class org.alfresco.repo.security.permissions.PermissionCheckCollectionTest
class org.alfresco.repo.security.permissions.impl.AbstractPermissionTest
class org.alfresco.repo.site.CustomRoleTest
class org.alfresco.repo.jscript.ScriptSearchTest
class org.alfresco.repo.search.impl.querymodel.impl.db.NodePermissionAssessorPermissionsTest
class org.alfresco.repo.rule.BaseRuleTest
class org.alfresco.repo.domain.subscriptions.SubscriptionDAOTest
class org.alfresco.repo.search.impl.solr.SolrSQLJSONResultMetadataSetTest
class org.alfresco.util.debug.OutputSpacesStoreSystemTest
class org.alfresco.repo.security.authority.script.ScriptAuthorityServiceTest
class org.alfresco.repo.security.permissions.impl.AbstractReadPermissionTest
class org.alfresco.repo.action.executer.ExecuteAllRulesActionExecuterTest
class org.alfresco.repo.workflow.activiti.ActivitiWorkflowComponentTest
class org.alfresco.repo.content.filestore.FileIOTest
class org.alfresco.repo.dictionary.DictionaryLoadDAOTest
class org.alfresco.repo.rendition2.LocalSynchronousTransformClientIntegrationTest
class org.alfresco.repo.invitation.FullInvitationServiceImplTests
class org.alfresco.repo.action.executer.TransitionSimpleWorkflowActionExecuterTest
class org.alfresco.repo.workflow.activiti.ActivitiSmokeTest
class org.alfresco.repo.imap.RemoteLoadTester
class org.alfresco.repo.content.replication.AggregatingContentStoreTest
class org.alfresco.repo.cache.AbstractCacheFactoryTest
class org.alfresco.heartbeat.SessionsUsageDataCollectorTest
```

**Comment by tpage-alfresco** [comment]
Example failure message from Travis:
```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   OmittedTestClassFinderUnitTest.checkTestClassesReferencedInTestSuites:111 Found test classes which are not referenced by any test suite. expected:<[]> but was:<[class org.alfresco.repo.content.transform.RemoteTransformerClientTest, class org.alfresco.repo.tenant.MultiTAdminServiceImplTest, class org.alfresco.repo.solr.SOLRTrackingComponentUnitTest...
```

**Comment by tpage-alfresco** [comment]
I have updated all the tests and now the new unit test passes locally.  I either added the test to AllUnitTestsSuite if it passed and ran quickly, marked it with the appropriate NonBuildTests interface (e.g. NeverRunsTests) or marked the class as abstract (if appropriate).  I didn't investigate those tests that failed any further - there were quite a lot.

RemoteTransformerClientTest was a special case. It passed, but it took about 12 seconds to run and is marked as deprecated.  Consequently I decided not to add it to a test suite and instead marked it as a NeverRunsTests.

**Review by killerboot — APPROVED** [review]
Nice feature

**Pull request merged**
