### PR TITLE
LOC-303 Fix for this ticket - Fully updated and localised iptc-model.…

### PR DESCRIPTION
**Pull request by gbroadbent**
…properties file in 15 languages. (new languages are: Danish, Finnish, Swedish, Polish and Czech)

### CODE REVIEW

**Comment by montgolfiere** [comment]
@gbroadbent It seems the line-endings have changed (extra ^M character) causing large diffs. I'm not sure that was intentional.

Workaround for viewing in GitHub: https://github.com/Alfresco/alfresco-community-repo/pull/449?w=1

**Comment by gbroadbent** [comment]
Please let me check the files. I will be back shortly.

Best regards,

Gloria

From: montgolfiere ***@***.***>
Reply to: Alfresco/alfresco-community-repo ***@***.***>
Date: Wednesday, 12 May 2021 at 13:49
To: Alfresco/alfresco-community-repo ***@***.***>
Cc: Gloria Camino ***@***.***>, Mention ***@***.***>
Subject: Re: [Alfresco/alfresco-community-repo] LOC-303 Fix for this ticket - Fully updated and localised iptc-model.… (#449)


@gbroadbent<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgbroadbent&data=04%7C01%7C%7C4e7ff295c46b420183f008d915444ee3%7Ca92a627ee9ce48ba8edb6c64a4dbcf34%7C0%7C0%7C637564205398563543%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TfyMjuEqSk53RF0oXXSuXrQZtxy1EqGTMoRu2yClRE4%3D&reserved=0> It seems the line-endings have changed (extra ^M character) causing large diffs. I'm not sure that was intentional.

Workaround for viewing in GitHub: #449<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAlfresco%2Falfresco-community-repo%2Fpull%2F449&data=04%7C01%7C%7C4e7ff295c46b420183f008d915444ee3%7Ca92a627ee9ce48ba8edb6c64a4dbcf34%7C0%7C0%7C637564205398573497%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4bLS4moDgRDf5vPJWbKvv4naydsT9KB8XC36ceF60v8%3D&reserved=0>

**Comment by gbroadbent** [comment]
Jan, I see an issue in the output Unix vs PC. I guess it may have been a fault in the parser settings.

I will generate the target files again and create a PR later,  Sorry about this.

Gloria

From: montgolfiere ***@***.***>
Reply to: Alfresco/alfresco-community-repo ***@***.***>
Date: Wednesday, 12 May 2021 at 13:49
To: Alfresco/alfresco-community-repo ***@***.***>
Cc: Gloria Camino ***@***.***>, Mention ***@***.***>
Subject: Re: [Alfresco/alfresco-community-repo] LOC-303 Fix for this ticket - Fully updated and localised iptc-model.… (#449)


@gbroadbent<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgbroadbent&data=04%7C01%7C%7C4e7ff295c46b420183f008d915444ee3%7Ca92a627ee9ce48ba8edb6c64a4dbcf34%7C0%7C0%7C637564205398563543%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TfyMjuEqSk53RF0oXXSuXrQZtxy1EqGTMoRu2yClRE4%3D&reserved=0> It seems the line-endings have changed (extra ^M character) causing large diffs. I'm not sure that was intentional.

Workaround for viewing in GitHub: #449<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAlfresco%2Falfresco-community-repo%2Fpull%2F449&data=04%7C01%7C%7C4e7ff295c46b420183f008d915444ee3%7Ca92a627ee9ce48ba8edb6c64a4dbcf34%7C0%7C0%7C637564205398573497%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4bLS4moDgRDf5vPJWbKvv4naydsT9KB8XC36ceF60v8%3D&reserved=0>

**Review by KikoUK — APPROVED** [review]

**Comment by montgolfiere** [comment]
Thanks @gbroadbent

**Review by montgolfiere — APPROVED** [review]
LGTM

**Pull request merged**
