### PR TITLE
WIP: DAUs content store mock - please keep - do not merge to master

### PR DESCRIPTION
**Pull request by SaraAspery**
This PR facilitates manual testing of Direct Access Urls without the need for a DAU supported content store such as S3 or Azure. It provides a mocked DAU in the file content store.

### CODE REVIEW

**Comment by montgolfiere** [comment]
FYI: @krdabrowski

**Comment by montgolfiere** [comment]
@SaraAspery Is this still needed. Can we close (without merge) to cleanup older unmerged PRs (and branches) ?

**Comment by SaraAspery** [comment]
> 
@montgolfiere It was intended to be useful to anyone who wishes to mock a DAU response without the need for an s3 connector. If you think it's no longer useful I will close it. I am not aware of any upcoming need for it :)

**Comment by montgolfiere** [comment]
I suggest closing.

**Comment by SaraAspery** [comment]
No longer required

**Pull request closed without merging**
