### PR TITLE
File name param for direct acccess url requests

### PR DESCRIPTION
**Pull request by tpage-alfresco**
Adds optional file name parameter for all direct access url requests https://github.com/Alfresco/alfresco-community-repo/issues/2064

### CODE REVIEW

**Comment by tpage-alfresco** [comment]
Creating a copy of the PR #2065 so that the build can run with credentials.

This PR should be merged with a merge commit to preserve the authorship from @canpan14.

**Comment by canpan14** [comment]
@tpage-alfresco That failure seems like an unrelated permissions issue on a test. Do you want me to investigate it or is it a known issue?

**Comment by tpage-alfresco** [comment]
Yes - this is a known issue with this test. Thank you for checking!

**Comment by tpage-alfresco** [comment]
Same known issue with `completeRecordsCantBeUpdated` - the rest of the build is good :+1:

**Comment by canpan14** [comment]
@tpage-alfresco Are there any other projects you want me to update outside of this and the API specs? I know there are a number of small libraries.

**Comment by tpage-alfresco** [comment]
> @tpage-alfresco Are there any other projects you want me to update outside of this and the API specs? I know there are a number of small libraries.

I think that's everything. I think we're waiting on the architectural review.

**Review by mpichura — APPROVED** [review]
LGTM

**Pull request merged**
